### ISSUE TITLE
`docker-compose build` fails because missing .env file.

### ISSUE THREAD

**Issue by cowlicks** [enigmampc/enigma-docker-network#2]
It fails with: 
```bash
Step 5/15 : RUN git clone -b $GIT_BRANCH_CORE --single-branch https://github.com/enigmampc/enigma-core.git
 ---> Running in 53b63f2b20c6
Cloning into 'enigma-core'...
fatal: Remote branch --single-branch not found in upstream origin
ERROR: Service 'core' failed to build: The command '/bin/sh -c git clone -b $GIT_BRANCH_CORE --single-branch https://github.com/enigmampc/enigma-core.git' returned a non-zero code: 128       
```
This happens because `GIT_BRANCH_CORE` isn't set. It used be set in the `.env` file, but this got renamed in d40493191 to `.env-template`. It looks like the template file is used to create the env file in `launch.bash`, but that is run after `docker-compose build` (according to the current docs). It seems like either the docs need updating, or there should be a preset env file.

(FYI the building isn't finished for me so this might need an update)

**Comment by lacabra** [comment]
Hi @cowlicks, thanks for reporting this. I have updated the documentation on the README (f40e8f8104cc906005d9c8f0abbd72f785d460b2) accordingly. No need to run `docker-compose build` separately, instead just start launching the network with `launch.bash`. When this script runs, it checks whether `.env` exists, and if it doesn't, it creates one from `.env-template`.
