### ISSUE TITLE
error after launch.bash

### ISSUE THREAD

**Issue by manolos** [enigmampc/enigma-docker-network#7]
Step 14/20 : RUN npm install
 ---> Running in 58015d0879a4
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 140.82.118.4]: errno=Connection refused
npm ERR! github.com[1: 140.82.118.3]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-04-18T11_47_23_222Z-debug.log
ERROR: Service 'contract' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
Build of docker images failed. Exiting.

**Comment by ycfung** [comment]
The developers said this repository has been deprecated. Please refer to this thread: https://forum.enigma.co/t/error-in-starting-the-enigma-docker-network/634/4

**Comment by lacabra** [comment]
Correct.

Having said that, this specific error seems like your connectivity dropped at the time when the images were building. I would double check the Internet connection in the host where you are building those images, and try again.
